### ISSUE TITLE
Running solver.solve() raises a StopIteration error

### ISSUE THREAD

**Issue by jbwincek** [adrianliaw/PyCuber#10]
The code I ran: 

``` python
import pycuber as pc
c = pc.Cube()
alg = pc.Formula()
random_alg = alg.random()
from pycuber.solver import CFOPSolver
solver = CFOPSolver(c)
solver.solve()
```

The error message it produced:

```
Cross:  Cross ......
Solving F2L#0 ......Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pycuber/solver/cfop/__init__.py", line 26, in solve
    f2l = next(f2lall)
StopIteration
```

I'm running Python 3.5.0, with the current release of PyCuber

**Comment by jbwincek** [comment]
That code sample is of course missing `c(random_alg)`, once that was added the issue went away. 
Sorry for opening a semi-non issue, though it might be worth it to check if the cube is solved before trying to solve it, or at least raising a more intelligible error than just StopIteration
